name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node_version: [12, 14, 16, 17]
        include:
          - os: macos-latest
            node_version: 16
          - os: windows-latest
            node_version: 16
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
